### ISSUE TITLE
Emoji Saver plugin 

### ISSUE THREAD

**Issue by bepvte** [bepvte/bd-addons#16]
### Discussed in https://github.com/bepvte/bd-addons/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **Syntruss** July 14, 2021</sup>
i have a lot of favorited emojis. every time discord crashes, I have to remember what they are and save them again. is there a way to make a plugin that remembers and keeps them when you crash? something like gif saver does? i think it would be very helpful. 

-syn</div>

**Comment by Syhix** [comment]
I would like to have emojis saved via a plugins :)

**Comment by eyebek** [comment]
hello, i'm having a problem with my discord since the latest update with the gifs being now saved in cloud with 250 limit. Everytime i try to open gif, emoji, or a sticker my discord crashes. It started happening after your latest plugin update. Do you have any ideas of what may cause those crashes? I used to have around 1600 gifs saved before, so I wonder if it's related to that?
![image](https://user-images.githubusercontent.com/81981592/141495753-a48984b0-f4c5-4849-8e22-cf704a7239a7.png)

**Comment by bepvte** [comment]
> hello, i'm having a problem with my discord since the latest update with the gifs being now saved in cloud with 250 limit. Everytime i try to open gif, emoji, or a sticker my discord crashes. It started happening after your latest plugin update. Do you have any ideas of what may cause those crashes? I used to have around 1600 gifs saved before, so I wonder if it's related to that? ![image](https://user-images.githubusercontent.com/81981592/141495753-a48984b0-f4c5-4849-8e22-cf704a7239a7.png)

#25

its not gifsaver. also not sure why this is on this issue and not its own

**Comment by eyebek** [comment]
> > hello, i'm having a problem with my discord since the latest update with the gifs being now saved in cloud with 250 limit. Everytime i try to open gif, emoji, or a sticker my discord crashes. It started happening after your latest plugin update. Do you have any ideas of what may cause those crashes? I used to have around 1600 gifs saved before, so I wonder if it's related to that? ![image](https://user-images.githubusercontent.com/81981592/141495753-a48984b0-f4c5-4849-8e22-cf704a7239a7.png)
> 
> #25
> 
> its not gifsaver. also not sure why this is on this issue and not its own

oh my bad didnt notice the other issue, but thanks anyway
