### ISSUE TITLE
CanaryLinks fails

### ISSUE THREAD

**Issue by actualdankcoder** [bepvte/bd-addons#29]
Upon importing the CanaryLinks plugin, an error occurs

    Uncaught (in promise) TypeError: Cannot read property 'exports' of undefined

The error tends to point to this segment of the code

      const copyLinkItem = WebpackModules.getByIndex(
        WebpackModules.getIndex(Filters.byDisplayName("useMessageCopyLinkItem"))
      );

**Comment by bepvte** [comment]
Discord started loading the right click menus code only when you right click on a message. Because plugins usually do all their work at startup, fixing this is very difficult for me right now. The BD guys are working on a way of making this easier to do, so for until then CanaryLinks will be a bit broken.
